### ISSUE TITLE
Update stylings to Products page

### ISSUE THREAD

**Issue by Hamdrive** [Hamdrive/FueledUp#10]
As products and Wishlist page share the same products card, there are some changes that were implemented on the wishlist page that can also be done on Products page.

1. Change height values
2. Add auto margins
3. Apply grid styling properties
4. Apply media queries to dynamically size cards for different screen sizes

**Comment by FarhanMobashir** [comment]
for the cart page i would to keep the product on top and then the order summary on small screen. you can simply flip those two.
![hamfuel](https://user-images.githubusercontent.com/43913808/153577546-27995d63-8a44-49fd-b4dc-334de5578973.png)

**Comment by Hamdrive** [comment]
> for the cart page i would to keep the product on top and then the order summary on small screen. you can simply flip those two. ![hamfuel](https://user-images.githubusercontent.com/43913808/153577546-27995d63-8a44-49fd-b4dc-334de5578973.png)

I believe the user would want to firstly see the total price and the breakup, hence have kept it the same.
